public enum Specialisation {
    CHEMSITRY,
    EARTH_SCIENCE,
    PHYSICS,
    ASTRONOMY,
    BIOLOGY,
    MEDICINE,
    ANTHROPOLOGY,
    PSYCHOLOGY,
    COMPUTER_SCIENCE,
    MATHEMATICS,
    STATISTICS,
    SYSTEM_SCIENCE,
    AGRICULTURE,
    ENGINEERING
}
